version: '3.8'

services:
  ffc-pay-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose"
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

volumes:
  azurite_data:
